### ISSUE TITLE
Migrate from legacy File-Based DB structure

### ISSUE THREAD

**Issue by Brodur** [eFiction/v5_1-vaporware#8]
Would it be possible to have a way to migrate an older e-fiction v3 site that is running on the file-based storage to move to database tables for stories?

More of a feature request than an issue.

**Comment by campZero** [comment]
This was one of the first things I built into it.
In other words: If the stories folder is where the installer can locate it, it will be used.
You can then either convert to full MySQL or use a filebased SQLite storage, which is still much better than single files.

**Comment by Brodur** [comment]
Right on, that's awesome. Thanks for following up on this!
